import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css';
import './../stylesheets/main.scss'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Movie List',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " " +"home"}>{children}</body>
    </html>
  )
}
